#![doc = "Peripheral access API for 602 microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
//extern "C" {}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    pub _handler: unsafe extern "C" fn(),
    pub _reserved: usize,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[unsafe(no_mangle)]
pub static __EXTERNAL_INTERRUPTS: [Vector; 0] = [];
#[doc = "glb."]
pub type Glb = crate::Periph<glb::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for Glb {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Glb").finish()
    }
}
#[doc = "glb."]
pub mod glb;
#[doc = "rf."]
pub type Rf = crate::Periph<rf::RegisterBlock, 0x4000_1000>;
impl core::fmt::Debug for Rf {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rf").finish()
    }
}
#[doc = "rf."]
pub mod rf;
#[doc = "gpip."]
pub type Gpip = crate::Periph<gpip::RegisterBlock, 0x4000_2000>;
impl core::fmt::Debug for Gpip {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpip").finish()
    }
}
#[doc = "gpip."]
pub mod gpip;
#[doc = "sec_dbg."]
pub type SecDbg = crate::Periph<sec_dbg::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for SecDbg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SecDbg").finish()
    }
}
#[doc = "sec_dbg."]
pub mod sec_dbg;
#[doc = "sec_eng."]
pub type SecEng = crate::Periph<sec_eng::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for SecEng {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SecEng").finish()
    }
}
#[doc = "sec_eng."]
pub mod sec_eng;
#[doc = "tzc_sec."]
pub type TzcSec = crate::Periph<tzc_sec::RegisterBlock, 0x4000_5000>;
impl core::fmt::Debug for TzcSec {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TzcSec").finish()
    }
}
#[doc = "tzc_sec."]
pub mod tzc_sec;
#[doc = "tzc_nsec."]
pub type TzcNsec = crate::Periph<tzc_nsec::RegisterBlock, 0x4000_6000>;
impl core::fmt::Debug for TzcNsec {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TzcNsec").finish()
    }
}
#[doc = "tzc_nsec."]
pub mod tzc_nsec;
#[doc = "ef_data_0."]
pub type EfData0 = crate::Periph<ef_data_0::RegisterBlock, 0x4000_7000>;
impl core::fmt::Debug for EfData0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EfData0").finish()
    }
}
#[doc = "ef_data_0."]
pub mod ef_data_0;
#[doc = "ef_data_1."]
pub type EfData1 = crate::Periph<ef_data_1::RegisterBlock, 0x4000_7000>;
impl core::fmt::Debug for EfData1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EfData1").finish()
    }
}
#[doc = "ef_data_1."]
pub mod ef_data_1;
#[doc = "ef_ctrl."]
pub type EfCtrl = crate::Periph<ef_ctrl::RegisterBlock, 0x4000_7000>;
impl core::fmt::Debug for EfCtrl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EfCtrl").finish()
    }
}
#[doc = "ef_ctrl."]
pub mod ef_ctrl;
#[doc = "cci."]
pub type Cci = crate::Periph<cci::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for Cci {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cci").finish()
    }
}
#[doc = "cci."]
pub mod cci;
#[doc = "l1c."]
pub type L1c = crate::Periph<l1c::RegisterBlock, 0x4000_9000>;
impl core::fmt::Debug for L1c {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("L1c").finish()
    }
}
#[doc = "l1c."]
pub mod l1c;
#[doc = "uart0."]
pub type Uart0 = crate::Periph<uart0::RegisterBlock, 0x4000_a000>;
impl core::fmt::Debug for Uart0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart0").finish()
    }
}
#[doc = "uart0."]
pub mod uart0;
#[doc = "uart1."]
pub type Uart1 = crate::Periph<uart1::RegisterBlock, 0x4000_a100>;
impl core::fmt::Debug for Uart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart1").finish()
    }
}
#[doc = "uart1."]
pub mod uart1;
#[doc = "spi."]
pub type Spi = crate::Periph<spi::RegisterBlock, 0x4000_a200>;
impl core::fmt::Debug for Spi {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi").finish()
    }
}
#[doc = "spi."]
pub mod spi;
#[doc = "i2c."]
pub type I2c = crate::Periph<i2c::RegisterBlock, 0x4000_a300>;
impl core::fmt::Debug for I2c {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c").finish()
    }
}
#[doc = "i2c."]
pub mod i2c;
#[doc = "pwm."]
pub type Pwm = crate::Periph<pwm::RegisterBlock, 0x4000_a400>;
impl core::fmt::Debug for Pwm {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm").finish()
    }
}
#[doc = "pwm."]
pub mod pwm;
#[doc = "timer."]
pub type Timer = crate::Periph<timer::RegisterBlock, 0x4000_a500>;
impl core::fmt::Debug for Timer {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer").finish()
    }
}
#[doc = "timer."]
pub mod timer;
#[doc = "ir."]
pub type Ir = crate::Periph<ir::RegisterBlock, 0x4000_a600>;
impl core::fmt::Debug for Ir {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ir").finish()
    }
}
#[doc = "ir."]
pub mod ir;
#[doc = "cks."]
pub type Cks = crate::Periph<cks::RegisterBlock, 0x4000_a000>;
impl core::fmt::Debug for Cks {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cks").finish()
    }
}
#[doc = "cks."]
pub mod cks;
#[doc = "sf_ctrl."]
pub type SfCtrl = crate::Periph<sf_ctrl::RegisterBlock, 0x4000_b000>;
impl core::fmt::Debug for SfCtrl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SfCtrl").finish()
    }
}
#[doc = "sf_ctrl."]
pub mod sf_ctrl;
#[doc = "dma."]
pub type Dma = crate::Periph<dma::RegisterBlock, 0x4000_c000>;
impl core::fmt::Debug for Dma {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dma").finish()
    }
}
#[doc = "dma."]
pub mod dma;
#[doc = "pds."]
pub type Pds = crate::Periph<pds::RegisterBlock, 0x4000_e000>;
impl core::fmt::Debug for Pds {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pds").finish()
    }
}
#[doc = "pds."]
pub mod pds;
#[doc = "HBN."]
pub type Hbn = crate::Periph<hbn::RegisterBlock, 0x4000_f000>;
impl core::fmt::Debug for Hbn {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Hbn").finish()
    }
}
#[doc = "HBN."]
pub mod hbn;
#[doc = "AON."]
pub type Aon = crate::Periph<aon::RegisterBlock, 0x4000_f800>;
impl core::fmt::Debug for Aon {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Aon").finish()
    }
}
#[doc = "AON."]
pub mod aon;
#[unsafe(no_mangle)]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "glb"]
    pub glb: Glb,
    #[doc = "rf"]
    pub rf: Rf,
    #[doc = "gpip"]
    pub gpip: Gpip,
    #[doc = "sec_dbg"]
    pub sec_dbg: SecDbg,
    #[doc = "sec_eng"]
    pub sec_eng: SecEng,
    #[doc = "tzc_sec"]
    pub tzc_sec: TzcSec,
    #[doc = "tzc_nsec"]
    pub tzc_nsec: TzcNsec,
    #[doc = "ef_data_0"]
    pub ef_data_0: EfData0,
    #[doc = "ef_data_1"]
    pub ef_data_1: EfData1,
    #[doc = "ef_ctrl"]
    pub ef_ctrl: EfCtrl,
    #[doc = "cci"]
    pub cci: Cci,
    #[doc = "l1c"]
    pub l1c: L1c,
    #[doc = "uart0"]
    pub uart0: Uart0,
    #[doc = "uart1"]
    pub uart1: Uart1,
    #[doc = "spi"]
    pub spi: Spi,
    #[doc = "i2c"]
    pub i2c: I2c,
    #[doc = "pwm"]
    pub pwm: Pwm,
    #[doc = "timer"]
    pub timer: Timer,
    #[doc = "ir"]
    pub ir: Ir,
    #[doc = "cks"]
    pub cks: Cks,
    #[doc = "sf_ctrl"]
    pub sf_ctrl: SfCtrl,
    #[doc = "dma"]
    pub dma: Dma,
    #[doc = "pds"]
    pub pds: Pds,
    #[doc = "HBN"]
    pub hbn: Hbn,
    #[doc = "AON"]
    pub aon: Aon,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        unsafe {
            DEVICE_PERIPHERALS = true;
            Peripherals {
                glb: Glb::steal(),
                rf: Rf::steal(),
                gpip: Gpip::steal(),
                sec_dbg: SecDbg::steal(),
                sec_eng: SecEng::steal(),
                tzc_sec: TzcSec::steal(),
                tzc_nsec: TzcNsec::steal(),
                ef_data_0: EfData0::steal(),
                ef_data_1: EfData1::steal(),
                ef_ctrl: EfCtrl::steal(),
                cci: Cci::steal(),
                l1c: L1c::steal(),
                uart0: Uart0::steal(),
                uart1: Uart1::steal(),
                spi: Spi::steal(),
                i2c: I2c::steal(),
                pwm: Pwm::steal(),
                timer: Timer::steal(),
                ir: Ir::steal(),
                cks: Cks::steal(),
                sf_ctrl: SfCtrl::steal(),
                dma: Dma::steal(),
                pds: Pds::steal(),
                hbn: Hbn::steal(),
                aon: Aon::steal(),
            }
        }
    }
}
