[package]
name = "statistical-testing-desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.53", features=["derive"]}
crc = "3.3.0"
indicatif = "0.18.3"
nistrs = { path = "../nistrs" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = {version = "1.0.145", features=["raw_value"]}
serialport = "4.8.1"
thousands = "0.2.0"
