[target.riscv32imafc-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tmemory.x", # memory.x must appear BEFORE link.x
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Thal_defaults.x",
  "-C", "llvm-args=-align-all-functions=2", # four-byte alignment for functions
]

[build]
target="riscv32imafc-unknown-none-elf"