[package]
name = "bare-metal"
version = "0.1.0"
edition = "2024"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "blinky"
path = "src/bin/blinky.rs"

[[bin]]
name = "button"
path = "src/bin/button.rs"

[[bin]]
name = "random"
path = "src/bin/random.rs"

[dependencies]
riscv = "0.15.0"
riscv-rt = { version= "0.16.0"}
bl602-hal = { path="../bl602-hal-suas" }
heapless = "0.9.1"